import { useState } from 'react';
import { Zap, Copy, Check, RotateCcw } from 'lucide-react';
import {
  loadAutopilotPolicy,
  saveAutopilotPolicy,
  applyPreset,
  formatAutopilotPolicyMarkdown,
  AUTOPILOT_PRESETS,
  AUTOPILOT_LEVEL_LABELS,
  AUTOPILOT_LEVEL_DESCRIPTIONS,
} from '../utils/darakeAutopilotPolicy';
import type { DarakeAutopilotLevel } from '../utils/darakeAutopilotPolicy';

type CopyState = 'idle' | 'copied' | 'failed';

const LEVELS: DarakeAutopilotLevel[] = [
  'manual-every-time',
  'batch-confirm',
  'safe-auto',
  'silent-safe-auto',
  'maximum-darake',
];

const AUTO_FIELDS: Array<{ key: keyof typeof AUTOPILOT_PRESETS['safe-auto']; label: string }> = [
  { key: 'autoProceedLocalDrafts', label: 'localドラフト生成' },
  { key: 'autoProceedCopyOnly', label: 'copy-only生成' },
  { key: 'autoProceedReports', label: 'レポート更新' },
  { key: 'autoProceedWarningsToBatch', label: 'warningのバッチ化' },
  { key: 'autoSelectBestOneAction', label: 'best action自動選択' },
  { key: 'autoGenerateNextInstructions', label: '次の指示書生成' },
  { key: 'autoGenerateDryRuns', label: 'dry-run生成' },
];

export function DarakeAutopilotPolicyPanel() {
  const [policy, setPolicy] = useState(() => loadAutopilotPolicy());
  const [copyState, setCopyState] = useState<CopyState>('idle');

  function handleSelectPreset(level: DarakeAutopilotLevel) {
    const next = applyPreset(level);
    saveAutopilotPolicy(next);
    setPolicy(next);
  }

  function handleReset() {
    const next = applyPreset('manual-every-time');
    saveAutopilotPolicy(next);
    setPolicy(next);
  }

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(formatAutopilotPolicyMarkdown(policy));
      setCopyState('copied');
      window.setTimeout(() => setCopyState('idle'), 1800);
    } catch {
      setCopyState('failed');
      window.setTimeout(() => setCopyState('idle'), 2400);
    }
  }

  return (
    <div className="phase33Panel">
      <div className="phase33Hero">
        <Zap />
        <div>
          <p className="eyebrow">Phase 33 / 33.1</p>
          <h3>Darake Autopilot Policy</h3>
          <p>OKを毎回押さなくてよいレベルを設定します。safe / draft / local は自動で進みます。</p>
        </div>
      </div>

      <div className="phase33SafetyBox">
        🔒 どのモードでも GitHub API・外部実行・secret保存・本番操作は一切しません。manual gate は人間確認必須のままです。
      </div>

      <div style={{ display: 'flex', alignItems: 'center', gap: 10, flexWrap: 'wrap' }}>
        <span style={{ fontSize: '0.82rem', color: 'var(--muted)' }}>現在のレベル:</span>
        <span className="phase33LevelBadge">⚡ {AUTOPILOT_LEVEL_LABELS[policy.level]}</span>
      </div>

      <div className="phase33Section">
        <h4>プリセット選択</h4>
        <div className="phase33PresetGrid">
          {LEVELS.map((level) => (
            <button
              key={level}
              className={`phase33PresetCard${policy.level === level ? ' active' : ''}`}
              onClick={() => handleSelectPreset(level)}
            >
              <p className="phase33PresetTitle">{AUTOPILOT_LEVEL_LABELS[level]}</p>
              <p className="phase33PresetDesc">{AUTOPILOT_LEVEL_DESCRIPTIONS[level]}</p>
            </button>
          ))}
        </div>
      </div>

      <div className="phase33Section">
        <h4>自動で進むもの</h4>
        <div className="phase33CheckGrid">
          {AUTO_FIELDS.map(({ key, label }) => (
            <div key={key} className="phase33CheckRow">
              <span>{label}</span>
              <span className={`phase33Badge ${policy[key] ? 'auto' : 'confirm'}`}>
                {policy[key] ? '✅ 自動' : '⏸ 確認'}
              </span>
            </div>
          ))}
        </div>
      </div>

      <div className="phase33Section">
        <h4>絶対に止まるもの（固定）</h4>
        <div className="phase33CheckGrid">
          {[
            'manual gate',
            '外部アクション',
            'secret / token',
            '本番deploy',
            'App Store Submit',
          ].map((label) => (
            <div key={label} className="phase33CheckRow">
              <span>{label}</span>
              <span className="phase33Badge fixed">🔒 人間確認必須</span>
            </div>
          ))}
        </div>
      </div>

      <div className="phase33SummaryGrid">
        <section>
          <h4>通知スタイル</h4>
          <p style={{ fontSize: '0.72rem' }}>{policy.notificationStyle}</p>
        </section>
        <section>
          <h4>確認頻度</h4>
          <p style={{ fontSize: '0.72rem' }}>{policy.humanCheckFrequency}</p>
        </section>
        <section>
          <h4>安全モード</h4>
          <p style={{ fontSize: '0.72rem' }}>{policy.fixedSafetyMode}</p>
        </section>
      </div>

      <div className="phase33BtnRow">
        <button
          className={`phase33CopyBtn ${copyState}`}
          onClick={() => void handleCopy()}
        >
          {copyState === 'copied' ? <Check size={14} /> : <Copy size={14} />} MDコピー
        </button>
        <button className="phase33SmallBtn" onClick={handleReset}>
          <RotateCcw size={13} /> 初期化
        </button>
      </div>
    </div>
  );
}
