export type IntegrationAuditItem = {
  id: string;
  phase: string;
  label: string;
  group: string;
  componentName: string;
  helperFiles: string[];
  cssFiles: string[];
  localStorageKeys: string[];
  safetyType:
    | 'copy-only'
    | 'manual-gate'
    | 'local-record'
    | 'draft-only'
    | 'readiness-gate'
    | 'report-only';
  externalAction: 'none' | 'draft-only';
  status: 'present' | 'needs-review' | 'missing' | 'unknown';
  notes: string;
};

export type CurrentIntegrationAudit = {
  title: string;
  status: 'healthy' | 'needs-review' | 'blocked';
  items: IntegrationAuditItem[];
  warnings: string[];
  blockers: string[];
  nextActions: string[];
};

export const INTEGRATION_AUDIT_ITEMS: IntegrationAuditItem[] = [
  // Phase 1-2: Seed / Blueprint
  {
    id: 'darake-mode',
    phase: '1-2',
    label: 'だらけモード設定',
    group: 'home',
    componentName: 'DarakeModePanel',
    helperFiles: [],
    cssFiles: ['darakeMode.css'],
    localStorageKeys: [],
    safetyType: 'copy-only',
    externalAction: 'none',
    status: 'present',
    notes: 'Phase 1/2のコアパネル。設定表示のみ。',
  },
  // Phase 3: Phase Queue
  {
    id: 'phase-queue',
    phase: '3',
    label: 'Phase Queue',
    group: 'create',
    componentName: 'PhaseQueuePanel',
    helperFiles: ['autoRunPhaseQueue.ts', 'phasePlanGenerator.ts'],
    cssFiles: ['phaseQueue.css'],
    localStorageKeys: ['darake.autoRunPhaseQueue.v1'],
    safetyType: 'manual-gate',
    externalAction: 'none',
    status: 'present',
    notes: 'Phase実行キュー管理。ローカル保存のみ。',
  },
  // Phase 4: Issue Draft
  {
    id: 'issue-draft',
    phase: '4',
    label: 'Issue Draft',
    group: 'create',
    componentName: 'IssueDraftPanel',
    helperFiles: ['draftStore.ts', 'formatIssueDraft.ts', 'issueNextStep.ts'],
    cssFiles: ['issueDraft.css'],
    localStorageKeys: ['darake.issueDraft.v1'],
    safetyType: 'copy-only',
    externalAction: 'none',
    status: 'present',
    notes: 'Issue下書き生成。コピーのみ、GitHub API不使用。',
  },
  {
    id: 'issue-record',
    phase: '4',
    label: 'Issue Record',
    group: 'create',
    componentName: 'IssueRecordPanel',
    helperFiles: ['issueRecordStore.ts'],
    cssFiles: ['issueRecord.css'],
    localStorageKeys: ['darake.issueRecord.v1'],
    safetyType: 'local-record',
    externalAction: 'none',
    status: 'present',
    notes: 'Issue記録。ローカル保存のみ。',
  },
  {
    id: 'final-check',
    phase: '4',
    label: 'Final Check',
    group: 'create',
    componentName: 'FinalCheckPanel',
    helperFiles: ['issueFinalConfirm.ts'],
    cssFiles: ['finalCheck.css'],
    localStorageKeys: [],
    safetyType: 'readiness-gate',
    externalAction: 'none',
    status: 'present',
    notes: '実行前チェック。表示・確認のみ。',
  },
  {
    id: 'manual-gate',
    phase: '4',
    label: 'Manual Gate',
    group: 'create',
    componentName: 'ManualGatePanel',
    helperFiles: [],
    cssFiles: ['manualGate.css'],
    localStorageKeys: [],
    safetyType: 'manual-gate',
    externalAction: 'none',
    status: 'present',
    notes: '手動確認ゲート。外部操作なし。',
  },
  // Phase 5: PR / Merge
  {
    id: 'pr-creation-preview',
    phase: '5',
    label: 'PR Creation Preview',
    group: 'run',
    componentName: 'PrCreationPreviewPanel',
    helperFiles: ['prCreationPreview.ts'],
    cssFiles: ['prCreationPreview.css'],
    localStorageKeys: ['darake.prCreationPreview.v1'],
    safetyType: 'copy-only',
    externalAction: 'none',
    status: 'present',
    notes: 'PR下書き生成。コピーのみ、GitHub API不使用。',
  },
  {
    id: 'low-risk-pr',
    phase: '5',
    label: 'Low Risk PR Candidate',
    group: 'run',
    componentName: 'LowRiskPrCandidatePanel',
    helperFiles: ['lowRiskPrCandidate.ts'],
    cssFiles: ['lowRiskPrCandidate.css'],
    localStorageKeys: ['darake.lowRiskPrCandidate.v1'],
    safetyType: 'manual-gate',
    externalAction: 'none',
    status: 'present',
    notes: '低リスクPR候補。手動確認のみ。',
  },
  {
    id: 'low-risk-merge',
    phase: '5',
    label: 'Low Risk Merge Candidate',
    group: 'run',
    componentName: 'LowRiskMergeCandidatePanel',
    helperFiles: ['lowRiskMergeCandidate.ts'],
    cssFiles: ['lowRiskMergeCandidate.css'],
    localStorageKeys: ['darake.lowRiskMergeCandidate.v1'],
    safetyType: 'manual-gate',
    externalAction: 'none',
    status: 'present',
    notes: '低リスクMerge候補。手動実行のみ。',
  },
  // Phase 6: Auto Run Plan
  {
    id: 'auto-run-plan',
    phase: '6',
    label: 'Auto Run Plan',
    group: 'create',
    componentName: 'AutoRunPlanPanel',
    helperFiles: ['autoRunPlanStore.ts', 'savedAutoRunPlanQueue.ts'],
    cssFiles: ['autoRunPlan.css'],
    localStorageKeys: ['darake.autoRunPlan.v1'],
    safetyType: 'draft-only',
    externalAction: 'none',
    status: 'present',
    notes: '実行計画下書き。ローカル保存のみ。',
  },
  // Phase 7: Safety / Review
  {
    id: 'phase7-safety',
    phase: '7',
    label: 'Phase 7 Safety',
    group: 'watch',
    componentName: 'Phase7SafetyPanel',
    helperFiles: ['darakeSafetySettings.ts'],
    cssFiles: ['phase7Safety.css'],
    localStorageKeys: [],
    safetyType: 'report-only',
    externalAction: 'none',
    status: 'present',
    notes: '安全設定確認。外部操作なし。',
  },
  {
    id: 'action-preview',
    phase: '7',
    label: 'Action Preview',
    group: 'watch',
    componentName: 'ActionPreviewPanel',
    helperFiles: ['issueActionPreview.ts'],
    cssFiles: ['actionPreview.css'],
    localStorageKeys: [],
    safetyType: 'report-only',
    externalAction: 'none',
    status: 'present',
    notes: '操作プレビュー表示のみ。',
  },
  // Phase 8: Preview URL / Watch
  {
    id: 'preview-url-record',
    phase: '8',
    label: 'Preview URL Record',
    group: 'watch',
    componentName: 'PreviewUrlRecordPanel',
    helperFiles: ['previewUrlStore.ts'],
    cssFiles: ['previewUrlRecord.css'],
    localStorageKeys: ['darake.previewUrl.v1'],
    safetyType: 'local-record',
    externalAction: 'none',
    status: 'present',
    notes: 'プレビューURL記録。ローカル保存のみ。',
  },
  {
    id: 'review-watch',
    phase: '8',
    label: 'Review Watch',
    group: 'watch',
    componentName: 'ReviewWatchPanel',
    helperFiles: ['reviewAlert.ts', 'reviewLanes.ts'],
    cssFiles: ['reviewWatch.css'],
    localStorageKeys: [],
    safetyType: 'report-only',
    externalAction: 'none',
    status: 'present',
    notes: 'レビュー状態確認。表示のみ。',
  },
  {
    id: 'pr-watch',
    phase: '8',
    label: 'PR Watch',
    group: 'run',
    componentName: 'PrWatchPanel',
    helperFiles: ['prAlert.ts', 'prLanes.ts'],
    cssFiles: ['prWatch.css'],
    localStorageKeys: [],
    safetyType: 'report-only',
    externalAction: 'none',
    status: 'present',
    notes: 'PR状態確認。表示のみ。',
  },
  {
    id: 'ci-watch',
    phase: '8',
    label: 'CI Watch',
    group: 'run',
    componentName: 'CiWatchPanel',
    helperFiles: ['ciAlert.ts', 'ciLanes.ts'],
    cssFiles: ['ciWatch.css'],
    localStorageKeys: [],
    safetyType: 'report-only',
    externalAction: 'none',
    status: 'present',
    notes: 'CI状態確認。表示のみ。',
  },
  // Phase 9: Screenshot base
  {
    id: 'screenshot-job-draft',
    phase: '9',
    label: 'Screenshot Job Draft',
    group: 'screenshots',
    componentName: 'ScreenshotJobDraftPanel',
    helperFiles: ['screenshotJobDraft.ts'],
    cssFiles: ['screenshotJobDraft.css'],
    localStorageKeys: ['darake.screenshotJobDraft.v1'],
    safetyType: 'draft-only',
    externalAction: 'none',
    status: 'present',
    notes: 'スクショジョブ下書き。ローカル保存のみ。',
  },
  {
    id: 'screenshot-plan-export',
    phase: '9',
    label: 'Screenshot Plan Export',
    group: 'screenshots',
    componentName: 'ScreenshotPlanExportPanel',
    helperFiles: ['screenshotPlanExport.ts'],
    cssFiles: ['screenshotPlanExport.css'],
    localStorageKeys: [],
    safetyType: 'copy-only',
    externalAction: 'none',
    status: 'present',
    notes: 'スクショ計画エクスポート。コピーのみ。',
  },
  {
    id: 'screenshot-run-gate',
    phase: '9',
    label: 'Screenshot Run Gate',
    group: 'screenshots',
    componentName: 'ScreenshotRunGatePanel',
    helperFiles: ['screenshotRunGate.ts'],
    cssFiles: ['screenshotRunGate.css'],
    localStorageKeys: [],
    safetyType: 'readiness-gate',
    externalAction: 'none',
    status: 'present',
    notes: 'スクショ実行ゲート。手動確認のみ。',
  },
  // Phase 10: Screenshot / UI Check
  {
    id: 'screenshot-workflow-dispatch',
    phase: '10',
    label: 'Screenshot Workflow Dispatch Draft',
    group: 'screenshots',
    componentName: 'ScreenshotWorkflowDispatchDraftPanel',
    helperFiles: ['screenshotWorkflowDispatchDraft.ts'],
    cssFiles: ['screenshotWorkflowDispatchDraft.css'],
    localStorageKeys: ['darake.screenshotWorkflowDispatch.v1'],
    safetyType: 'copy-only',
    externalAction: 'draft-only',
    status: 'present',
    notes: 'Workflow dispatch下書き。コピーのみ、実行しない。',
  },
  {
    id: 'screenshot-workflow-file-status',
    phase: '10',
    label: 'Screenshot Workflow File Status',
    group: 'screenshots',
    componentName: 'ScreenshotWorkflowFileStatusPanel',
    helperFiles: ['screenshotWorkflowFileStatus.ts'],
    cssFiles: ['screenshotWorkflowFileStatus.css'],
    localStorageKeys: ['darake.screenshotWorkflowFileStatus.v1'],
    safetyType: 'local-record',
    externalAction: 'none',
    status: 'present',
    notes: 'Workflowファイル状態記録。',
  },
  {
    id: 'screenshot-workflow-manual-run-guide',
    phase: '10',
    label: 'Screenshot Workflow Manual Run Guide',
    group: 'screenshots',
    componentName: 'ScreenshotWorkflowManualRunGuidePanel',
    helperFiles: ['screenshotWorkflowManualRunGuide.ts'],
    cssFiles: ['screenshotWorkflowManualRunGuide.css'],
    localStorageKeys: [],
    safetyType: 'manual-gate',
    externalAction: 'none',
    status: 'present',
    notes: '手動実行ガイド。コピーのみ。',
  },
  {
    id: 'screenshot-dry-run-artifact',
    phase: '10',
    label: 'Screenshot Dry Run Artifact Check',
    group: 'screenshots',
    componentName: 'ScreenshotDryRunArtifactCheckPanel',
    helperFiles: ['screenshotDryRunArtifactCheck.ts'],
    cssFiles: ['screenshotDryRunArtifactCheck.css'],
    localStorageKeys: [],
    safetyType: 'readiness-gate',
    externalAction: 'none',
    status: 'present',
    notes: 'Dry run成果物確認。',
  },
  {
    id: 'dry-run-artifact-record',
    phase: '10',
    label: 'Dry Run Artifact Check Record',
    group: 'screenshots',
    componentName: 'DryRunArtifactCheckRecordPanel',
    helperFiles: ['dryRunArtifactCheckRecord.ts'],
    cssFiles: ['dryRunArtifactCheckRecord.css'],
    localStorageKeys: ['darake.dryRunArtifactCheckRecord.v1'],
    safetyType: 'local-record',
    externalAction: 'none',
    status: 'present',
    notes: 'Dry run成果物記録。',
  },
  {
    id: 'screenshot-capture-gate',
    phase: '10',
    label: 'Screenshot Capture Gate',
    group: 'screenshots',
    componentName: 'ScreenshotCaptureGatePanel',
    helperFiles: ['screenshotCaptureGate.ts'],
    cssFiles: ['screenshotCaptureGate.css'],
    localStorageKeys: [],
    safetyType: 'readiness-gate',
    externalAction: 'none',
    status: 'present',
    notes: 'スクショ撮影ゲート確認。',
  },
  {
    id: 'real-capture-workflow',
    phase: '10',
    label: 'Real Capture Workflow Draft',
    group: 'screenshots',
    componentName: 'RealCaptureWorkflowDraftPanel',
    helperFiles: ['screenshotRealCaptureWorkflowDraft.ts'],
    cssFiles: ['realCaptureWorkflowDraft.css'],
    localStorageKeys: ['darake.realCaptureWorkflowDraft.v1'],
    safetyType: 'draft-only',
    externalAction: 'none',
    status: 'present',
    notes: '実撮影workflow下書き。',
  },
  {
    id: 'playwright-dry-run',
    phase: '10',
    label: 'Playwright Setup Dry Run Draft',
    group: 'screenshots',
    componentName: 'PlaywrightSetupDryRunDraftPanel',
    helperFiles: ['playwrightSetupDryRunDraft.ts'],
    cssFiles: ['playwrightSetupDryRunDraft.css'],
    localStorageKeys: ['darake.playwrightSetupDryRunDraft.v1'],
    safetyType: 'draft-only',
    externalAction: 'none',
    status: 'present',
    notes: 'Playwright dry run下書き。',
  },
  {
    id: 'playwright-workflow-status',
    phase: '10',
    label: 'Playwright Setup Workflow File Status',
    group: 'screenshots',
    componentName: 'PlaywrightSetupWorkflowFileStatusPanel',
    helperFiles: ['playwrightSetupWorkflowFileStatus.ts'],
    cssFiles: ['playwrightSetupWorkflowFileStatus.css'],
    localStorageKeys: ['darake.playwrightSetupWorkflowFileStatus.v1'],
    safetyType: 'local-record',
    externalAction: 'none',
    status: 'present',
    notes: 'Playwright workflowファイル状態。',
  },
  {
    id: 'playwright-manual-run-guide',
    phase: '10',
    label: 'Playwright Setup Manual Run Guide',
    group: 'screenshots',
    componentName: 'PlaywrightSetupManualRunGuidePanel',
    helperFiles: ['playwrightSetupManualRunGuide.ts'],
    cssFiles: ['playwrightSetupManualRunGuide.css'],
    localStorageKeys: [],
    safetyType: 'manual-gate',
    externalAction: 'none',
    status: 'present',
    notes: 'Playwright手動実行ガイド。',
  },
  {
    id: 'playwright-report-record',
    phase: '10',
    label: 'Playwright Setup Report Record',
    group: 'screenshots',
    componentName: 'PlaywrightSetupReportRecordPanel',
    helperFiles: ['playwrightSetupReportRecord.ts'],
    cssFiles: ['playwrightSetupReportRecord.css'],
    localStorageKeys: ['darake.playwrightSetupReportRecord.v1'],
    safetyType: 'local-record',
    externalAction: 'none',
    status: 'present',
    notes: 'Playwright実行記録。',
  },
  {
    id: 'limited-screenshot-workflow',
    phase: '10',
    label: 'Limited Screenshot Capture Workflow Draft',
    group: 'screenshots',
    componentName: 'LimitedScreenshotCaptureWorkflowDraftPanel',
    helperFiles: ['limitedScreenshotCaptureWorkflowDraft.ts'],
    cssFiles: ['limitedScreenshotCaptureWorkflowDraft.css'],
    localStorageKeys: ['darake.limitedScreenshotCaptureWorkflowDraft.v1'],
    safetyType: 'draft-only',
    externalAction: 'none',
    status: 'present',
    notes: '限定スクショworkflow下書き。',
  },
  {
    id: 'limited-screenshot-file-status',
    phase: '10',
    label: 'Limited Screenshot Capture Workflow File Status',
    group: 'screenshots',
    componentName: 'LimitedScreenshotCaptureWorkflowFileStatusPanel',
    helperFiles: ['limitedScreenshotCaptureWorkflowFileStatus.ts'],
    cssFiles: ['limitedScreenshotCaptureWorkflowFileStatus.css'],
    localStorageKeys: ['darake.limitedScreenshotCaptureWorkflowFileStatus.v1'],
    safetyType: 'local-record',
    externalAction: 'none',
    status: 'present',
    notes: '限定スクショファイル状態。',
  },
  {
    id: 'limited-screenshot-manual-guide',
    phase: '10',
    label: 'Limited Screenshot Capture Manual Run Guide',
    group: 'screenshots',
    componentName: 'LimitedScreenshotCaptureManualRunGuidePanel',
    helperFiles: ['limitedScreenshotCaptureManualRunGuide.ts'],
    cssFiles: ['limitedScreenshotCaptureManualRunGuide.css'],
    localStorageKeys: [],
    safetyType: 'manual-gate',
    externalAction: 'none',
    status: 'present',
    notes: '限定スクショ手動実行ガイド。',
  },
  {
    id: 'screenshot-manifest-record',
    phase: '10.26',
    label: 'Screenshot Capture Manifest Record',
    group: 'screenshots',
    componentName: 'ScreenshotCaptureManifestRecordPanel',
    helperFiles: ['screenshotCaptureManifestRecord.ts'],
    cssFiles: ['screenshotCaptureManifestRecord.css'],
    localStorageKeys: ['darake.screenshotCaptureManifest.v1'],
    safetyType: 'local-record',
    externalAction: 'none',
    status: 'present',
    notes: 'スクショマニフェスト記録。',
  },
  {
    id: 'screenshot-manifest-result-bridge',
    phase: '10.27',
    label: 'Screenshot Manifest to Result Bridge',
    group: 'screenshots',
    componentName: 'ScreenshotManifestToResultBridgePanel',
    helperFiles: ['screenshotManifestToResultBridge.ts'],
    cssFiles: ['screenshotManifestToResultBridge.css'],
    localStorageKeys: [],
    safetyType: 'readiness-gate',
    externalAction: 'none',
    status: 'present',
    notes: 'マニフェスト→結果橋渡し。',
  },
  {
    id: 'screenshot-result-record',
    phase: '10.27',
    label: 'Screenshot Result Record',
    group: 'screenshots',
    componentName: 'ScreenshotResultRecordPanel',
    helperFiles: ['screenshotResultRecord.ts'],
    cssFiles: ['screenshotResultRecord.css'],
    localStorageKeys: ['darake.screenshotResultRecord.v1'],
    safetyType: 'local-record',
    externalAction: 'none',
    status: 'present',
    notes: 'スクショ結果記録。',
  },
  {
    id: 'ui-check-readiness-gate',
    phase: '10.28',
    label: 'UI Check Readiness Gate',
    group: 'screenshots',
    componentName: 'UiCheckReadinessGatePanel',
    helperFiles: ['uiCheckReadinessGate.ts'],
    cssFiles: ['uiCheckReadinessGate.css'],
    localStorageKeys: [],
    safetyType: 'readiness-gate',
    externalAction: 'none',
    status: 'present',
    notes: 'UIチェック準備ゲート。',
  },
  {
    id: 'screenshot-to-ui-check-bridge',
    phase: '10.28',
    label: 'Screenshot to UI Check Bridge',
    group: 'screenshots',
    componentName: 'ScreenshotToUiCheckBridgePanel',
    helperFiles: ['screenshotToUiCheckResult.ts'],
    cssFiles: ['screenshotToUiCheckBridge.css'],
    localStorageKeys: [],
    safetyType: 'readiness-gate',
    externalAction: 'none',
    status: 'present',
    notes: 'スクショ→UIチェック橋渡し。',
  },
  {
    id: 'ui-machine-check-draft',
    phase: '10.29',
    label: 'UI Machine Check Draft',
    group: 'screenshots',
    componentName: 'UiMachineCheckDraftPanel',
    helperFiles: ['uiMachineCheckDraft.ts'],
    cssFiles: ['uiMachineCheckDraft.css'],
    localStorageKeys: ['darake.uiMachineCheckDraft.v1'],
    safetyType: 'draft-only',
    externalAction: 'none',
    status: 'present',
    notes: 'UIマシンチェック下書き。',
  },
  {
    id: 'ui-machine-check-input-pack',
    phase: '10.29',
    label: 'UI Machine Check Input Pack',
    group: 'screenshots',
    componentName: 'UiMachineCheckInputPackPanel',
    helperFiles: ['uiMachineCheckInputPack.ts'],
    cssFiles: ['uiMachineCheckInputPack.css'],
    localStorageKeys: [],
    safetyType: 'copy-only',
    externalAction: 'none',
    status: 'present',
    notes: 'UIマシンチェック入力パック生成。',
  },
  {
    id: 'ui-check-result-bridge',
    phase: '10.30',
    label: 'UI Check Result Bridge',
    group: 'screenshots',
    componentName: 'UiCheckResultBridgePanel',
    helperFiles: ['uiCheckResultBridge.ts'],
    cssFiles: ['uiCheckResultBridge.css'],
    localStorageKeys: [],
    safetyType: 'readiness-gate',
    externalAction: 'none',
    status: 'present',
    notes: 'UIチェック結果橋渡し。',
  },
  {
    id: 'ui-check-result-record',
    phase: '10.30',
    label: 'UI Check Result Record',
    group: 'screenshots',
    componentName: 'UiCheckResultRecordPanel',
    helperFiles: ['uiCheckResultRecord.ts'],
    cssFiles: ['uiCheckResultRecord.css'],
    localStorageKeys: ['darake.uiCheckResultRecord.v1'],
    safetyType: 'local-record',
    externalAction: 'none',
    status: 'present',
    notes: 'UIチェック結果記録。',
  },
  {
    id: 'ui-check-completion-report',
    phase: '10.30',
    label: 'UI Check Completion Report',
    group: 'screenshots',
    componentName: 'UiCheckCompletionReportPanel',
    helperFiles: ['uiCheckCompletionReport.ts'],
    cssFiles: ['uiCheckCompletionReport.css'],
    localStorageKeys: [],
    safetyType: 'report-only',
    externalAction: 'none',
    status: 'present',
    notes: 'UIチェック完成レポート。',
  },
  {
    id: 'phase10-completion-report',
    phase: '10',
    label: 'Phase 10 Screenshot UI Completion Report',
    group: 'screenshots',
    componentName: 'Phase10ScreenshotUiCompletionReportPanel',
    helperFiles: ['phase10ScreenshotUiCompletionReport.ts'],
    cssFiles: ['phase10ScreenshotUiCompletionReport.css'],
    localStorageKeys: [],
    safetyType: 'report-only',
    externalAction: 'none',
    status: 'present',
    notes: 'Phase 10完成レポート。',
  },
  // Phase 11: Notification System
  {
    id: 'notification-draft',
    phase: '11',
    label: 'Notification Draft',
    group: 'submit',
    componentName: 'NotificationDraftPanel',
    helperFiles: ['notificationEventModel.ts'],
    cssFiles: ['notificationDraft.css'],
    localStorageKeys: ['darake.notificationDraft.v1'],
    safetyType: 'draft-only',
    externalAction: 'none',
    status: 'present',
    notes: '通知下書き。実送信しない。',
  },
  {
    id: 'notification-digest',
    phase: '11',
    label: 'Notification Digest',
    group: 'submit',
    componentName: 'NotificationDigestPanel',
    helperFiles: ['notificationDigest.ts'],
    cssFiles: ['notificationDigest.css'],
    localStorageKeys: [],
    safetyType: 'report-only',
    externalAction: 'none',
    status: 'present',
    notes: '通知ダイジェスト表示。',
  },
  {
    id: 'manual-gate-notification',
    phase: '11',
    label: 'Manual Gate Notification Template',
    group: 'submit',
    componentName: 'ManualGateNotificationTemplatePanel',
    helperFiles: ['manualGateNotificationTemplates.ts'],
    cssFiles: ['notificationDraft.css'],
    localStorageKeys: [],
    safetyType: 'copy-only',
    externalAction: 'none',
    status: 'present',
    notes: '手動ゲート通知テンプレート。コピーのみ。',
  },
  // Phase 12: App Store Prep
  {
    id: 'app-store-metadata',
    phase: '12',
    label: 'App Store Metadata Draft',
    group: 'submit',
    componentName: 'AppStoreMetadataDraftPanel',
    helperFiles: ['appStoreMetadataDraft.ts'],
    cssFiles: ['appStoreMetadataDraft.css'],
    localStorageKeys: ['darake.appStoreMetadata.v1'],
    safetyType: 'draft-only',
    externalAction: 'none',
    status: 'present',
    notes: 'App Storeメタデータ下書き。',
  },
  {
    id: 'store-copy-template',
    phase: '12',
    label: 'Store Copy Template',
    group: 'submit',
    componentName: 'StoreCopyTemplatePanel',
    helperFiles: ['storeCopyTemplates.ts'],
    cssFiles: ['appStoreMetadataDraft.css'],
    localStorageKeys: [],
    safetyType: 'copy-only',
    externalAction: 'none',
    status: 'present',
    notes: 'ストアコピーテンプレート。コピーのみ。',
  },
  {
    id: 'privacy-age-rating',
    phase: '12',
    label: 'Privacy Age Rating Draft',
    group: 'submit',
    componentName: 'PrivacyAgeRatingDraftPanel',
    helperFiles: ['privacyAgeRatingDraft.ts'],
    cssFiles: ['appStoreMetadataDraft.css'],
    localStorageKeys: ['darake.privacyAgeRating.v1'],
    safetyType: 'draft-only',
    externalAction: 'none',
    status: 'present',
    notes: 'プライバシー・年齢制限下書き。',
  },
  {
    id: 'app-store-screenshot-checklist',
    phase: '12',
    label: 'App Store Screenshot Checklist',
    group: 'submit',
    componentName: 'AppStoreScreenshotChecklistPanel',
    helperFiles: ['appStoreScreenshotChecklist.ts'],
    cssFiles: ['appStoreMetadataDraft.css'],
    localStorageKeys: [],
    safetyType: 'readiness-gate',
    externalAction: 'none',
    status: 'present',
    notes: 'App Storeスクショチェックリスト。',
  },
  {
    id: 'app-store-prep-completion',
    phase: '12',
    label: 'App Store Prep Completion Report',
    group: 'submit',
    componentName: 'AppStorePrepCompletionReportPanel',
    helperFiles: ['appStorePrepCompletionReport.ts'],
    cssFiles: ['appStoreMetadataDraft.css'],
    localStorageKeys: [],
    safetyType: 'report-only',
    externalAction: 'none',
    status: 'present',
    notes: 'App Store準備完成レポート。',
  },
  // Phase 13: Submission Control Room
  {
    id: 'submission-control-room',
    phase: '13',
    label: 'Submission Control Room',
    group: 'submit',
    componentName: 'SubmissionControlRoomPanel',
    helperFiles: ['submissionControlRoom.ts'],
    cssFiles: ['submissionControlRoom.css'],
    localStorageKeys: ['darake.submissionControlRoom.v1'],
    safetyType: 'manual-gate',
    externalAction: 'none',
    status: 'present',
    notes: '提出管制室。手動ゲート。',
  },
  {
    id: 'app-store-connect-input',
    phase: '13',
    label: 'App Store Connect Input Pack',
    group: 'submit',
    componentName: 'AppStoreConnectInputPackPanel',
    helperFiles: ['appStoreConnectInputPack.ts'],
    cssFiles: ['submissionControlRoom.css'],
    localStorageKeys: ['darake.appStoreConnectInputPack.v1'],
    safetyType: 'copy-only',
    externalAction: 'none',
    status: 'present',
    notes: 'App Store Connect入力パック。コピーのみ。',
  },
  {
    id: 'app-store-connect-api-candidate',
    phase: '13',
    label: 'App Store Connect API Candidate Draft',
    group: 'submit',
    componentName: 'AppStoreConnectApiCandidateDraftPanel',
    helperFiles: ['appStoreConnectApiCandidateDraft.ts'],
    cssFiles: ['submissionControlRoom.css'],
    localStorageKeys: [],
    safetyType: 'draft-only',
    externalAction: 'draft-only',
    status: 'present',
    notes: 'App Store Connect API候補下書き。実行しない。',
  },
  {
    id: 'test-flight-prep',
    phase: '13',
    label: 'TestFlight Prep Checklist',
    group: 'submit',
    componentName: 'TestFlightPrepChecklistPanel',
    helperFiles: ['testFlightPrepChecklist.ts'],
    cssFiles: ['submissionControlRoom.css'],
    localStorageKeys: [],
    safetyType: 'readiness-gate',
    externalAction: 'none',
    status: 'present',
    notes: 'TestFlight準備チェックリスト。',
  },
  {
    id: 'final-submission-gate',
    phase: '13',
    label: 'Final Submission Gate',
    group: 'submit',
    componentName: 'FinalSubmissionGatePanel',
    helperFiles: ['finalSubmissionGate.ts'],
    cssFiles: ['submissionControlRoom.css'],
    localStorageKeys: ['darake.finalSubmissionGate.v1'],
    safetyType: 'manual-gate',
    externalAction: 'none',
    status: 'present',
    notes: '最終提出ゲート。手動確認必須。',
  },
  {
    id: 'submit-for-review-guide',
    phase: '13',
    label: 'Submit for Review Manual Guide',
    group: 'submit',
    componentName: 'SubmitForReviewManualGuidePanel',
    helperFiles: ['submitForReviewManualGuide.ts'],
    cssFiles: ['submissionControlRoom.css'],
    localStorageKeys: [],
    safetyType: 'manual-gate',
    externalAction: 'none',
    status: 'present',
    notes: '審査提出手動ガイド。自動実行しない。',
  },
  // Phase 14: Rejection Control Room
  {
    id: 'rejection-record',
    phase: '14',
    label: 'App Review Rejection Record',
    group: 'submit',
    componentName: 'AppReviewRejectionRecordPanel',
    helperFiles: ['appReviewRejectionRecord.ts', 'appReviewRejectionClassifier.ts'],
    cssFiles: ['rejectionControlRoom.css'],
    localStorageKeys: ['darake.appReviewRejection.v1'],
    safetyType: 'local-record',
    externalAction: 'none',
    status: 'present',
    notes: 'リジェクト記録。ローカル保存のみ。',
  },
  {
    id: 'rejection-response-draft',
    phase: '14',
    label: 'App Review Response Draft',
    group: 'submit',
    componentName: 'AppReviewResponseDraftPanel',
    helperFiles: ['appReviewResponseDraft.ts'],
    cssFiles: ['rejectionControlRoom.css'],
    localStorageKeys: ['darake.appReviewResponseDraft.v1'],
    safetyType: 'draft-only',
    externalAction: 'none',
    status: 'present',
    notes: '審査回答下書き。コピーのみ。',
  },
  {
    id: 'rejection-fix-issue',
    phase: '14',
    label: 'Rejection Fix Issue Draft',
    group: 'submit',
    componentName: 'RejectionFixIssueDraftPanel',
    helperFiles: ['rejectionFixIssueDraft.ts'],
    cssFiles: ['rejectionControlRoom.css'],
    localStorageKeys: ['darake.rejectionFixIssueDraft.v1'],
    safetyType: 'copy-only',
    externalAction: 'none',
    status: 'present',
    notes: 'リジェクト修正Issue下書き。コピーのみ。',
  },
  {
    id: 'resubmission-checklist',
    phase: '14',
    label: 'Resubmission Checklist',
    group: 'submit',
    componentName: 'ResubmissionChecklistPanel',
    helperFiles: ['resubmissionChecklist.ts'],
    cssFiles: ['rejectionControlRoom.css'],
    localStorageKeys: [],
    safetyType: 'readiness-gate',
    externalAction: 'none',
    status: 'present',
    notes: '再提出チェックリスト。',
  },
  // Phase 15: Post-Release Operations
  {
    id: 'release-record',
    phase: '15',
    label: 'Release Record',
    group: 'post-release',
    componentName: 'ReleaseRecordPanel',
    helperFiles: ['releaseRecord.ts'],
    cssFiles: ['phase15to18.css'],
    localStorageKeys: ['darake.releaseRecord.v1'],
    safetyType: 'local-record',
    externalAction: 'none',
    status: 'present',
    notes: 'リリース記録。ローカル保存のみ。',
  },
  {
    id: 'post-release-feedback',
    phase: '15',
    label: 'Post Release Feedback',
    group: 'post-release',
    componentName: 'PostReleaseFeedbackPanel',
    helperFiles: ['postReleaseFeedbackRecord.ts'],
    cssFiles: ['phase15to18.css'],
    localStorageKeys: ['darake.postReleaseFeedback.v1'],
    safetyType: 'local-record',
    externalAction: 'none',
    status: 'present',
    notes: 'リリース後フィードバック記録。',
  },
  {
    id: 'feedback-issue-draft',
    phase: '15',
    label: 'Feedback Issue Draft',
    group: 'post-release',
    componentName: 'FeedbackIssueDraftPanel',
    helperFiles: ['feedbackIssueDraft.ts'],
    cssFiles: ['phase15to18.css'],
    localStorageKeys: [],
    safetyType: 'copy-only',
    externalAction: 'none',
    status: 'present',
    notes: 'フィードバックIssue下書き。コピーのみ。',
  },
  {
    id: 'next-update-plan',
    phase: '15',
    label: 'Next Update Plan',
    group: 'post-release',
    componentName: 'NextUpdatePlanPanel',
    helperFiles: ['nextUpdatePlan.ts'],
    cssFiles: ['phase15to18.css'],
    localStorageKeys: ['darake.nextUpdatePlan.v1'],
    safetyType: 'draft-only',
    externalAction: 'none',
    status: 'present',
    notes: '次回更新計画。ローカル保存のみ。',
  },
  {
    id: 'post-release-completion',
    phase: '15',
    label: 'Post Release Completion Report',
    group: 'post-release',
    componentName: 'PostReleaseCompletionReportPanel',
    helperFiles: ['postReleaseCompletionReport.ts'],
    cssFiles: ['phase15to18.css'],
    localStorageKeys: [],
    safetyType: 'report-only',
    externalAction: 'none',
    status: 'present',
    notes: 'リリース後完成レポート。',
  },
  // Phase 16: Portfolio Control Room
  {
    id: 'darake-home-summary',
    phase: '16',
    label: 'Darake Home Summary',
    group: 'home',
    componentName: 'DarakeHomeSummaryPanel',
    helperFiles: ['darakeHomeSummary.ts', 'appRegistry.ts', 'releaseRecord.ts'],
    cssFiles: ['phase15to18.css'],
    localStorageKeys: ['darake.appRegistry.v1', 'darake.releaseRecord.v1'],
    safetyType: 'report-only',
    externalAction: 'none',
    status: 'present',
    notes: 'ホームサマリー。表示のみ。',
  },
  {
    id: 'app-registry',
    phase: '16',
    label: 'App Registry',
    group: 'portfolio',
    componentName: 'AppRegistryPanel',
    helperFiles: ['appRegistry.ts'],
    cssFiles: ['phase15to18.css'],
    localStorageKeys: ['darake.appRegistry.v1'],
    safetyType: 'local-record',
    externalAction: 'none',
    status: 'present',
    notes: 'アプリ一覧登録。ローカル保存のみ。',
  },
  {
    id: 'portfolio-dashboard',
    phase: '16',
    label: 'Portfolio Dashboard',
    group: 'portfolio',
    componentName: 'PortfolioDashboardPanel',
    helperFiles: ['portfolioDashboard.ts'],
    cssFiles: ['phase15to18.css'],
    localStorageKeys: [],
    safetyType: 'report-only',
    externalAction: 'none',
    status: 'present',
    notes: 'ポートフォリオ概要。',
  },
  {
    id: 'todays-focus',
    phase: '16',
    label: "Today's Focus",
    group: 'portfolio',
    componentName: 'TodaysFocusPanel',
    helperFiles: ['todaysFocusSelector.ts'],
    cssFiles: ['phase15to18.css'],
    localStorageKeys: [],
    safetyType: 'report-only',
    externalAction: 'none',
    status: 'present',
    notes: '今日のフォーカス表示。',
  },
  {
    id: 'cross-app-notification',
    phase: '16',
    label: 'Cross App Notification Digest',
    group: 'portfolio',
    componentName: 'CrossAppNotificationDigestPanel',
    helperFiles: ['crossAppNotificationDigest.ts'],
    cssFiles: ['phase15to18.css'],
    localStorageKeys: [],
    safetyType: 'report-only',
    externalAction: 'none',
    status: 'present',
    notes: 'クロスアプリ通知ダイジェスト。',
  },
  {
    id: 'portfolio-completion',
    phase: '16',
    label: 'Portfolio Completion Report',
    group: 'portfolio',
    componentName: 'PortfolioCompletionReportPanel',
    helperFiles: ['portfolioCompletionReport.ts'],
    cssFiles: ['phase15to18.css'],
    localStorageKeys: [],
    safetyType: 'report-only',
    externalAction: 'none',
    status: 'present',
    notes: 'ポートフォリオ完成レポート。',
  },
  // Phase 17: Template Factory
  {
    id: 'blueprint-generator',
    phase: '17',
    label: 'Blueprint Generator',
    group: 'templates',
    componentName: 'BlueprintGeneratorPanel',
    helperFiles: ['appBlueprintTemplates.ts', 'ideaToBlueprintConverter.ts'],
    cssFiles: ['phase15to18.css'],
    localStorageKeys: [],
    safetyType: 'copy-only',
    externalAction: 'none',
    status: 'present',
    notes: '設計書生成。コピーのみ。',
  },
  {
    id: 'cloud-agent-instruction-generator',
    phase: '17',
    label: 'Cloud Agent Instruction Generator',
    group: 'templates',
    componentName: 'CloudAgentInstructionGeneratorPanel',
    helperFiles: ['cloudAgentInstructionGenerator.ts'],
    cssFiles: ['phase15to18.css'],
    localStorageKeys: [],
    safetyType: 'copy-only',
    externalAction: 'none',
    status: 'present',
    notes: 'Cloud Agent指示書生成。コピーのみ。',
  },
  {
    id: 'issue-draft-batch',
    phase: '17',
    label: 'Issue Draft Batch Generator',
    group: 'templates',
    componentName: 'IssueDraftBatchGeneratorPanel',
    helperFiles: ['issueDraftBatchGenerator.ts'],
    cssFiles: ['phase15to18.css'],
    localStorageKeys: [],
    safetyType: 'copy-only',
    externalAction: 'none',
    status: 'present',
    notes: 'Issue下書きバッチ生成。コピーのみ。',
  },
  {
    id: 'saved-blueprints',
    phase: '17',
    label: 'Saved Blueprints',
    group: 'templates',
    componentName: 'SavedBlueprintsPanel',
    helperFiles: ['savedBlueprints.ts'],
    cssFiles: ['phase15to18.css'],
    localStorageKeys: ['darake.savedBlueprints.v1'],
    safetyType: 'local-record',
    externalAction: 'none',
    status: 'present',
    notes: '保存済み設計書。ローカル保存のみ。',
  },
  // Phase 18: Darake Dev OS
  {
    id: 'darake-safety-settings',
    phase: '18',
    label: 'Darake Safety Settings',
    group: 'settings',
    componentName: 'DarakeSafetySettingsPanel',
    helperFiles: ['darakeSafetySettings.ts'],
    cssFiles: ['phase15to18.css'],
    localStorageKeys: ['darake.safetySettings.v1'],
    safetyType: 'manual-gate',
    externalAction: 'none',
    status: 'present',
    notes: '安全設定管理。ローカル保存のみ。',
  },
  {
    id: 'darake-dev-os-completion',
    phase: '18',
    label: 'Darake Dev OS Completion Report',
    group: 'reports',
    componentName: 'DarakeDevOsCompletionReportPanel',
    helperFiles: ['darakeDevOsCompletionReport.ts'],
    cssFiles: ['phase15to18.css'],
    localStorageKeys: [],
    safetyType: 'report-only',
    externalAction: 'none',
    status: 'present',
    notes: 'Darake Dev OS完成レポート。',
  },
  // Phase 19: External Notification Candidate
  {
    id: 'external-notification-channel',
    phase: '19',
    label: 'External Notification Channel',
    group: 'settings',
    componentName: 'ExternalNotificationChannelPanel',
    helperFiles: ['externalNotificationChannels.ts'],
    cssFiles: ['phase19to23.css'],
    localStorageKeys: ['darake.externalNotificationChannels.v1'],
    safetyType: 'draft-only',
    externalAction: 'none',
    status: 'present',
    notes: '外部通知チャンネル設定。実送信しない。',
  },
  {
    id: 'webhook-payload-draft',
    phase: '19',
    label: 'Webhook Payload Draft',
    group: 'settings',
    componentName: 'WebhookPayloadDraftPanel',
    helperFiles: ['webhookPayloadDraft.ts'],
    cssFiles: ['phase19to23.css'],
    localStorageKeys: ['darake.webhookPayloadDraft.v1'],
    safetyType: 'draft-only',
    externalAction: 'draft-only',
    status: 'present',
    notes: 'Webhook payloadドラフト。実送信しない。',
  },
  {
    id: 'manual-notification-guide',
    phase: '19',
    label: 'Manual Notification Send Guide',
    group: 'create',
    componentName: 'ManualNotificationSendGuidePanel',
    helperFiles: ['manualNotificationSendGuide.ts'],
    cssFiles: ['phase19to23.css'],
    localStorageKeys: [],
    safetyType: 'manual-gate',
    externalAction: 'none',
    status: 'present',
    notes: '手動通知送信ガイド。コピーのみ。',
  },
  {
    id: 'external-notification-completion',
    phase: '19',
    label: 'External Notification Completion Report',
    group: 'reports',
    componentName: 'ExternalNotificationCompletionReportPanel',
    helperFiles: ['externalNotificationCompletionReport.ts'],
    cssFiles: ['phase19to23.css'],
    localStorageKeys: [],
    safetyType: 'report-only',
    externalAction: 'none',
    status: 'present',
    notes: '外部通知準備完成レポート。',
  },
  // Phase 20: GitHub Semi-Automation
  {
    id: 'github-operation-candidate',
    phase: '20',
    label: 'GitHub Operation Candidate',
    group: 'run',
    componentName: 'GitHubOperationCandidatePanel',
    helperFiles: ['githubOperationCandidate.ts'],
    cssFiles: ['phase19to23.css'],
    localStorageKeys: ['darake.githubOperationCandidate.v1'],
    safetyType: 'manual-gate',
    externalAction: 'none',
    status: 'present',
    notes: 'GitHub操作候補。手動確認のみ。GitHub API自動実行なし。',
  },
  {
    id: 'workflow-dispatch-candidate',
    phase: '20',
    label: 'Workflow Dispatch Candidate Draft',
    group: 'run',
    componentName: 'WorkflowDispatchCandidateDraftPanel',
    helperFiles: ['workflowDispatchCandidateDraft.ts'],
    cssFiles: ['phase19to23.css'],
    localStorageKeys: ['darake.workflowDispatchCandidate.v1'],
    safetyType: 'manual-gate',
    externalAction: 'draft-only',
    status: 'present',
    notes: 'workflow dispatch候補。下書きのみ、実行しない。',
  },
  {
    id: 'pr-merge-candidate-gate',
    phase: '20',
    label: 'PR Merge Candidate Gate',
    group: 'run',
    componentName: 'PrMergeCandidateGatePanel',
    helperFiles: ['prMergeCandidateGate.ts'],
    cssFiles: ['phase19to23.css'],
    localStorageKeys: [],
    safetyType: 'manual-gate',
    externalAction: 'none',
    status: 'present',
    notes: 'PRマージ候補ゲート。手動確認必須。',
  },
  {
    id: 'github-manual-operation-guide',
    phase: '20',
    label: 'GitHub Manual Operation Guide',
    group: 'run',
    componentName: 'GitHubManualOperationGuidePanel',
    helperFiles: ['githubManualOperationGuide.ts'],
    cssFiles: ['phase19to23.css'],
    localStorageKeys: [],
    safetyType: 'manual-gate',
    externalAction: 'none',
    status: 'present',
    notes: 'GitHub手動操作ガイド。コピーのみ。',
  },
  {
    id: 'github-semi-automation-completion',
    phase: '20',
    label: 'GitHub Semi-Automation Completion Report',
    group: 'reports',
    componentName: 'GitHubSemiAutomationCompletionReportPanel',
    helperFiles: ['githubSemiAutomationCompletionReport.ts'],
    cssFiles: ['phase19to23.css'],
    localStorageKeys: [],
    safetyType: 'report-only',
    externalAction: 'none',
    status: 'present',
    notes: 'GitHub半自動化完成レポート。',
  },
  // Phase 21: AI Review Integration
  {
    id: 'ai-review-input-pack',
    phase: '21',
    label: 'AI Review Input Pack',
    group: 'create',
    componentName: 'AiReviewInputPackPanel',
    helperFiles: ['aiReviewInputPack.ts'],
    cssFiles: ['phase19to23.css'],
    localStorageKeys: ['darake.aiReviewInputPack.v1'],
    safetyType: 'copy-only',
    externalAction: 'none',
    status: 'present',
    notes: 'AIレビュー入力パック生成。コピーのみ、AI API不使用。',
  },
  {
    id: 'screenshot-ai-review-prompt',
    phase: '21',
    label: 'Screenshot AI Review Prompt Builder',
    group: 'screenshots',
    componentName: 'ScreenshotAiReviewPromptBuilderPanel',
    helperFiles: ['screenshotAiReviewPromptBuilder.ts'],
    cssFiles: ['phase19to23.css'],
    localStorageKeys: [],
    safetyType: 'copy-only',
    externalAction: 'none',
    status: 'present',
    notes: 'スクショAIレビュープロンプト生成。コピーのみ。',
  },
  {
    id: 'ai-review-result-record',
    phase: '21',
    label: 'AI Review Result Record',
    group: 'watch',
    componentName: 'AiReviewResultRecordPanel',
    helperFiles: ['aiReviewResultRecord.ts'],
    cssFiles: ['phase19to23.css'],
    localStorageKeys: ['darake.aiReviewResultRecord.v1'],
    safetyType: 'local-record',
    externalAction: 'none',
    status: 'present',
    notes: 'AIレビュー結果記録。ローカル保存のみ。',
  },
  {
    id: 'ai-review-fix-issue',
    phase: '21',
    label: 'AI Review Fix Issue Draft',
    group: 'create',
    componentName: 'AiReviewFixIssueDraftPanel',
    helperFiles: ['aiReviewFixIssueDraft.ts'],
    cssFiles: ['phase19to23.css'],
    localStorageKeys: ['darake.aiReviewFixIssueDraft.v1'],
    safetyType: 'copy-only',
    externalAction: 'none',
    status: 'present',
    notes: 'AIレビュー修正Issue下書き。コピーのみ。',
  },
  {
    id: 'ai-review-completion',
    phase: '21',
    label: 'AI Review Completion Report',
    group: 'reports',
    componentName: 'AiReviewCompletionReportPanel',
    helperFiles: ['aiReviewCompletionReport.ts'],
    cssFiles: ['phase19to23.css'],
    localStorageKeys: [],
    safetyType: 'report-only',
    externalAction: 'none',
    status: 'present',
    notes: 'AIレビュー完成レポート。',
  },
  // Phase 22: Revenue & Operations Notes
  {
    id: 'monetization-plan',
    phase: '22',
    label: 'Monetization Plan',
    group: 'reports',
    componentName: 'MonetizationPlanPanel',
    helperFiles: ['monetizationPlan.ts'],
    cssFiles: ['phase19to23.css'],
    localStorageKeys: ['darake.monetizationPlan.v1'],
    safetyType: 'draft-only',
    externalAction: 'none',
    status: 'present',
    notes: '収益化計画メモ。ローカル保存のみ。',
  },
  {
    id: 'operation-cost-checklist',
    phase: '22',
    label: 'Operation Cost Checklist',
    group: 'reports',
    componentName: 'OperationCostChecklistPanel',
    helperFiles: ['operationCostChecklist.ts'],
    cssFiles: ['phase19to23.css'],
    localStorageKeys: [],
    safetyType: 'report-only',
    externalAction: 'none',
    status: 'present',
    notes: '運用コストチェックリスト。',
  },
  {
    id: 'launch-promotion-memo',
    phase: '22',
    label: 'Launch Promotion Memo',
    group: 'reports',
    componentName: 'LaunchPromotionMemoPanel',
    helperFiles: ['launchPromotionMemo.ts'],
    cssFiles: ['phase19to23.css'],
    localStorageKeys: ['darake.launchPromotionMemo.v1'],
    safetyType: 'draft-only',
    externalAction: 'none',
    status: 'present',
    notes: 'ローンチプロモーションメモ。',
  },
  {
    id: 'revenue-operations-report',
    phase: '22',
    label: 'Revenue & Operations Report',
    group: 'reports',
    componentName: 'RevenueOperationsReportPanel',
    helperFiles: ['revenueOperationsReport.ts'],
    cssFiles: ['phase19to23.css'],
    localStorageKeys: [],
    safetyType: 'report-only',
    externalAction: 'none',
    status: 'present',
    notes: '収益・運用レポート。',
  },
  // Phase 23: App Studio Factory Mode
  {
    id: 'app-idea-batch',
    phase: '23',
    label: 'App Idea Batch',
    group: 'create',
    componentName: 'AppIdeaBatchPanel',
    helperFiles: ['appIdeaBatch.ts'],
    cssFiles: ['phase19to23.css'],
    localStorageKeys: ['darake.appIdeaBatch.v1'],
    safetyType: 'draft-only',
    externalAction: 'none',
    status: 'present',
    notes: 'アプリアイデア一括生成。',
  },
  {
    id: 'idea-to-blueprint-converter',
    phase: '23',
    label: 'Idea to Blueprint Converter',
    group: 'templates',
    componentName: 'IdeaToBlueprintConverterPanel',
    helperFiles: ['ideaToBlueprintConverter.ts'],
    cssFiles: ['phase19to23.css'],
    localStorageKeys: [],
    safetyType: 'copy-only',
    externalAction: 'none',
    status: 'present',
    notes: 'アイデア→設計書変換。コピーのみ。',
  },
  {
    id: 'app-factory-roadmap',
    phase: '23',
    label: 'App Factory Roadmap',
    group: 'templates',
    componentName: 'AppFactoryRoadmapPanel',
    helperFiles: ['appFactoryRoadmap.ts'],
    cssFiles: ['phase19to23.css'],
    localStorageKeys: ['darake.appFactoryRoadmap.v1'],
    safetyType: 'draft-only',
    externalAction: 'none',
    status: 'present',
    notes: 'アプリファクトリーロードマップ。',
  },
  {
    id: 'app-factory-completion',
    phase: '23',
    label: 'App Studio Factory Completion Report',
    group: 'reports',
    componentName: 'AppFactoryCompletionReportPanel',
    helperFiles: ['appFactoryCompletionReport.ts'],
    cssFiles: ['phase19to23.css'],
    localStorageKeys: [],
    safetyType: 'report-only',
    externalAction: 'none',
    status: 'present',
    notes: 'App Studio Factory完成レポート。',
  },
  // Phase 24: Integration Audit
  {
    id: 'current-integration-audit',
    phase: '24',
    label: 'Current Integration Audit',
    group: 'reports',
    componentName: 'CurrentIntegrationAuditPanel',
    helperFiles: ['currentIntegrationAudit.ts'],
    cssFiles: ['currentIntegrationAudit.css'],
    localStorageKeys: [],
    safetyType: 'report-only',
    externalAction: 'none',
    status: 'present',
    notes: 'Phase 1〜23の統合監査レポート。',
  },
  {
    id: 'safety-invariant-audit',
    phase: '24',
    label: 'Safety Invariant Audit',
    group: 'settings',
    componentName: 'SafetyInvariantAuditPanel',
    helperFiles: ['safetyInvariantAudit.ts'],
    cssFiles: ['safetyInvariantAudit.css'],
    localStorageKeys: [],
    safetyType: 'report-only',
    externalAction: 'none',
    status: 'present',
    notes: '安全不変条件監査。外部操作なし。',
  },
  {
    id: 'localstorage-key-registry',
    phase: '24',
    label: 'LocalStorage Key Registry',
    group: 'settings',
    componentName: 'LocalStorageKeyRegistryPanel',
    helperFiles: ['localStorageKeyRegistry.ts'],
    cssFiles: ['localStorageKeyRegistry.css'],
    localStorageKeys: [],
    safetyType: 'report-only',
    externalAction: 'none',
    status: 'present',
    notes: 'localStorageキー一覧。機密データなし。',
  },
  {
    id: 'phase24-completion',
    phase: '24',
    label: 'Phase 24 Integration Completion Report',
    group: 'reports',
    componentName: 'Phase24IntegrationCompletionReportPanel',
    helperFiles: ['phase24IntegrationCompletionReport.ts'],
    cssFiles: ['phase24IntegrationCompletionReport.css'],
    localStorageKeys: [],
    safetyType: 'report-only',
    externalAction: 'none',
    status: 'present',
    notes: 'Phase 24統合完成レポート。',
  },
];

export function buildCurrentIntegrationAudit(): CurrentIntegrationAudit {
  const items = INTEGRATION_AUDIT_ITEMS;
  const warnings: string[] = [];
  const blockers: string[] = [];

  const unknownItems = items.filter((i) => i.status === 'unknown');
  const reviewItems = items.filter((i) => i.status === 'needs-review');
  const missingItems = items.filter((i) => i.status === 'missing');

  if (unknownItems.length > 0) {
    warnings.push(`${unknownItems.length}件のパネルがステータス不明です。`);
  }
  if (reviewItems.length > 0) {
    warnings.push(`${reviewItems.length}件のパネルが要確認です。`);
  }
  if (missingItems.length > 0) {
    blockers.push(`${missingItems.length}件のパネルが見つかりません。`);
  }

  const draftOnlyExternalItems = items.filter((i) => i.externalAction === 'draft-only');
  if (draftOnlyExternalItems.length > 0) {
    warnings.push(
      `${draftOnlyExternalItems.length}件のパネルがdraft-only外部操作候補を持ちます（実行はしません）。`,
    );
  }

  const overallStatus: CurrentIntegrationAudit['status'] =
    blockers.length > 0 ? 'blocked' : warnings.length > 0 ? 'needs-review' : 'healthy';

  const nextActions: string[] = [
    'Phase 24.3: NavigationBarとFocused Modeの実運用化を確認する',
    'Phase 24.5: Safety Invariant Auditで安全方針を確認する',
    'Phase 24.6: LocalStorage Key Registryでキー衝突を確認する',
    'Phase 24.7: Completion Reportで全体状況を把握する',
  ];

  return {
    title: 'Current Integration Audit - Phase 1〜24',
    status: overallStatus,
    items,
    warnings,
    blockers,
    nextActions,
  };
}

export function formatCurrentIntegrationAuditMarkdown(audit: CurrentIntegrationAudit): string {
  const lines: string[] = [
    `# ${audit.title}`,
    `Status: ${audit.status}`,
    '',
    '## パネル一覧',
  ];

  const byPhase = new Map<string, IntegrationAuditItem[]>();
  for (const item of audit.items) {
    const key = `Phase ${item.phase}`;
    if (!byPhase.has(key)) byPhase.set(key, []);
    byPhase.get(key)!.push(item);
  }

  for (const [phase, phaseItems] of byPhase) {
    lines.push(`\n### ${phase}`);
    for (const item of phaseItems) {
      lines.push(
        `- **${item.label}** (${item.componentName}) [${item.group}] [${item.safetyType}] [${item.status}]`,
      );
    }
  }

  if (audit.warnings.length > 0) {
    lines.push('\n## Warnings');
    audit.warnings.forEach((w) => lines.push(`- ⚠️ ${w}`));
  }
  if (audit.blockers.length > 0) {
    lines.push('\n## Blockers');
    audit.blockers.forEach((b) => lines.push(`- 🔴 ${b}`));
  }
  lines.push('\n## Next Actions');
  audit.nextActions.forEach((a) => lines.push(`- ${a}`));

  return lines.join('\n');
}
