// Phase 33: Darake Autopilot Policy

export type DarakeAutopilotLevel =
  | 'manual-every-time'
  | 'batch-confirm'
  | 'safe-auto'
  | 'silent-safe-auto'
  | 'maximum-darake';

export type DarakeAutopilotPolicy = {
  level: DarakeAutopilotLevel;
  autoProceedLocalDrafts: boolean;
  autoProceedCopyOnly: boolean;
  autoProceedReports: boolean;
  autoProceedWarningsToBatch: boolean;
  autoSelectBestOneAction: boolean;
  autoGenerateNextInstructions: boolean;
  autoGenerateDryRuns: boolean;
  requireHumanForManualGate: boolean;
  requireHumanForExternalAction: boolean;
  requireHumanForSecrets: boolean;
  requireHumanForProduction: boolean;
  requireHumanForAppStoreSubmit: boolean;
  notificationStyle:
    | 'none-until-blocked'
    | 'completion-only'
    | 'manual-gate-only'
    | 'normal'
    | 'strict';
  humanCheckFrequency:
    | 'never-for-safe'
    | 'daily-summary'
    | 'session-summary'
    | 'each-manual-gate'
    | 'every-action';
  fixedSafetyMode: 'strict-manual-gate';
};

// Fixed safety overrides that apply to ALL levels
const FIXED_SAFETY: Pick<
  DarakeAutopilotPolicy,
  | 'requireHumanForManualGate'
  | 'requireHumanForExternalAction'
  | 'requireHumanForSecrets'
  | 'requireHumanForProduction'
  | 'requireHumanForAppStoreSubmit'
  | 'fixedSafetyMode'
> = {
  requireHumanForManualGate: true,
  requireHumanForExternalAction: true,
  requireHumanForSecrets: true,
  requireHumanForProduction: true,
  requireHumanForAppStoreSubmit: true,
  fixedSafetyMode: 'strict-manual-gate',
};

export const AUTOPILOT_PRESETS: Record<DarakeAutopilotLevel, DarakeAutopilotPolicy> = {
  'manual-every-time': {
    level: 'manual-every-time',
    autoProceedLocalDrafts: false,
    autoProceedCopyOnly: false,
    autoProceedReports: false,
    autoProceedWarningsToBatch: false,
    autoSelectBestOneAction: false,
    autoGenerateNextInstructions: false,
    autoGenerateDryRuns: false,
    notificationStyle: 'strict',
    humanCheckFrequency: 'every-action',
    ...FIXED_SAFETY,
  },
  'batch-confirm': {
    level: 'batch-confirm',
    autoProceedLocalDrafts: false,
    autoProceedCopyOnly: true,
    autoProceedReports: true,
    autoProceedWarningsToBatch: true,
    autoSelectBestOneAction: false,
    autoGenerateNextInstructions: false,
    autoGenerateDryRuns: true,
    notificationStyle: 'normal',
    humanCheckFrequency: 'session-summary',
    ...FIXED_SAFETY,
  },
  'safe-auto': {
    level: 'safe-auto',
    autoProceedLocalDrafts: true,
    autoProceedCopyOnly: true,
    autoProceedReports: true,
    autoProceedWarningsToBatch: true,
    autoSelectBestOneAction: true,
    autoGenerateNextInstructions: true,
    autoGenerateDryRuns: true,
    notificationStyle: 'manual-gate-only',
    humanCheckFrequency: 'each-manual-gate',
    ...FIXED_SAFETY,
  },
  'silent-safe-auto': {
    level: 'silent-safe-auto',
    autoProceedLocalDrafts: true,
    autoProceedCopyOnly: true,
    autoProceedReports: true,
    autoProceedWarningsToBatch: true,
    autoSelectBestOneAction: true,
    autoGenerateNextInstructions: true,
    autoGenerateDryRuns: true,
    notificationStyle: 'completion-only',
    humanCheckFrequency: 'daily-summary',
    ...FIXED_SAFETY,
  },
  'maximum-darake': {
    level: 'maximum-darake',
    autoProceedLocalDrafts: true,
    autoProceedCopyOnly: true,
    autoProceedReports: true,
    autoProceedWarningsToBatch: true,
    autoSelectBestOneAction: true,
    autoGenerateNextInstructions: true,
    autoGenerateDryRuns: true,
    notificationStyle: 'none-until-blocked',
    humanCheckFrequency: 'never-for-safe',
    ...FIXED_SAFETY,
  },
};

export const AUTOPILOT_LEVEL_LABELS: Record<DarakeAutopilotLevel, string> = {
  'manual-every-time': '毎回確認（従来）',
  'batch-confirm': 'まとめて確認',
  'safe-auto': 'safe自動 / manual gateのみ確認',
  'silent-safe-auto': 'サイレント自動 / blockedのみ表示',
  'maximum-darake': '最大だらけ（blocked だけ前に出す）',
};

export const AUTOPILOT_LEVEL_DESCRIPTIONS: Record<DarakeAutopilotLevel, string> = {
  'manual-every-time': '毎回OKを求めます。従来の動作と同じです。',
  'batch-confirm': '細かいOKは求めず、セッション終わりにまとめて確認します。',
  'safe-auto': 'local / draft / copy / report は自動で進め、manual gateのみ確認します。',
  'silent-safe-auto': 'safe-autoよりさらに静か。manual gateも即通知せず、completionにまとめます。blockedのみ表示。',
  'maximum-darake': '最大だらけモード。safe/draft/local/copy-only全自動。warningは最後。manual gateはキューに溜める。blockedだけ前に出す。',
};

const STORAGE_KEY = 'darake.autopilotPolicy.v1';

export function loadAutopilotPolicy(): DarakeAutopilotPolicy {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return AUTOPILOT_PRESETS['manual-every-time'];
    const parsed = JSON.parse(raw) as DarakeAutopilotPolicy;
    // Always enforce fixed safety overrides
    return { ...parsed, ...FIXED_SAFETY };
  } catch {
    return AUTOPILOT_PRESETS['manual-every-time'];
  }
}

export function saveAutopilotPolicy(policy: DarakeAutopilotPolicy): void {
  try {
    // Always enforce fixed safety overrides before saving
    const safe: DarakeAutopilotPolicy = { ...policy, ...FIXED_SAFETY };
    localStorage.setItem(STORAGE_KEY, JSON.stringify(safe));
  } catch {
    // ignore
  }
}

export function applyPreset(level: DarakeAutopilotLevel): DarakeAutopilotPolicy {
  return { ...AUTOPILOT_PRESETS[level], ...FIXED_SAFETY };
}

export function formatAutopilotPolicyMarkdown(policy: DarakeAutopilotPolicy): string {
  const lines = [
    `# Darake Autopilot Policy`,
    '',
    `**レベル:** ${AUTOPILOT_LEVEL_LABELS[policy.level]} (${policy.level})`,
    `**説明:** ${AUTOPILOT_LEVEL_DESCRIPTIONS[policy.level]}`,
    '',
    `## 自動で進むもの`,
    `- localドラフト生成: ${policy.autoProceedLocalDrafts ? '✅ 自動' : '⏸ 確認'}`,
    `- copy-only生成: ${policy.autoProceedCopyOnly ? '✅ 自動' : '⏸ 確認'}`,
    `- レポート更新: ${policy.autoProceedReports ? '✅ 自動' : '⏸ 確認'}`,
    `- warningのバッチ化: ${policy.autoProceedWarningsToBatch ? '✅ 自動' : '⏸ 確認'}`,
    `- best action自動選択: ${policy.autoSelectBestOneAction ? '✅ 自動' : '⏸ 確認'}`,
    `- 次の指示書生成: ${policy.autoGenerateNextInstructions ? '✅ 自動' : '⏸ 確認'}`,
    `- dry-run生成: ${policy.autoGenerateDryRuns ? '✅ 自動' : '⏸ 確認'}`,
    '',
    `## 絶対に止まるもの（固定）`,
    `- manual gate: ✅ 人間確認必須`,
    `- 外部アクション: ✅ 人間確認必須`,
    `- secret / token: ✅ 人間確認必須`,
    `- 本番deploy: ✅ 人間確認必須`,
    `- App Store Submit: ✅ 人間確認必須`,
    '',
    `## 通知設定`,
    `- 通知スタイル: ${policy.notificationStyle}`,
    `- 人間確認頻度: ${policy.humanCheckFrequency}`,
    `- 固定安全モード: ${policy.fixedSafetyMode}`,
  ];
  return lines.join('\n');
}
