export type LocalStorageKeyRegistryItem = {
  key: string;
  owner: string;
  phase: string;
  purpose: string;
  containsSensitiveData: boolean;
  notes: string;
};

export const LOCAL_STORAGE_KEY_REGISTRY: LocalStorageKeyRegistryItem[] = [
  // Navigation / Focused Mode
  {
    key: 'darake.navGroup.v1',
    owner: 'DarakeNavigationBar / DarakeControlRoom',
    phase: '18 / 24',
    purpose: 'アクティブなナビグループを保存',
    containsSensitiveData: false,
    notes: 'DarakeNavGroupId | "all" の文字列値。',
  },
  {
    key: 'darake.focusedMode.v1',
    owner: 'FocusedModePanel / DarakeControlRoom',
    phase: '18 / 24',
    purpose: 'フォーカスモードIDを保存',
    containsSensitiveData: false,
    notes: 'FocusedModeId の文字列値。',
  },
  // Safety Settings
  {
    key: 'darake.safetySettings.v1',
    owner: 'DarakeSafetySettingsPanel',
    phase: '18',
    purpose: '安全設定（確認チェック状態）を保存',
    containsSensitiveData: false,
    notes: 'boolean フラグのみ。secret なし。',
  },
  // Issue Draft / Record
  {
    key: 'darake.issueDraft.v1',
    owner: 'IssueDraftPanel',
    phase: '4',
    purpose: 'Issue下書きの状態を保存',
    containsSensitiveData: false,
    notes: '下書きテキスト。GitHub tokenは含まない。',
  },
  {
    key: 'darake.issueRecord.v1',
    owner: 'IssueRecordPanel',
    phase: '4',
    purpose: 'Issue記録一覧を保存',
    containsSensitiveData: false,
    notes: 'Issue記録オブジェクトの配列。',
  },
  // PR
  {
    key: 'darake.prCreationPreview.v1',
    owner: 'PrCreationPreviewPanel',
    phase: '5',
    purpose: 'PR下書きの状態を保存',
    containsSensitiveData: false,
    notes: 'PR下書きテキスト。token含まない。',
  },
  {
    key: 'darake.lowRiskPrCandidate.v1',
    owner: 'LowRiskPrCandidatePanel',
    phase: '5',
    purpose: '低リスクPR候補設定を保存',
    containsSensitiveData: false,
    notes: 'リスク評価設定のみ。',
  },
  {
    key: 'darake.lowRiskMergeCandidate.v1',
    owner: 'LowRiskMergeCandidatePanel',
    phase: '5',
    purpose: '低リスクMerge候補設定を保存',
    containsSensitiveData: false,
    notes: 'リスク評価設定のみ。',
  },
  // Auto Run Plan / Phase Queue
  {
    key: 'darake.autoRunPlan.v1',
    owner: 'AutoRunPlanPanel',
    phase: '6',
    purpose: '実行計画下書きを保存',
    containsSensitiveData: false,
    notes: '計画テキスト。',
  },
  {
    key: 'darake.autoRunPhaseQueue.v1',
    owner: 'PhaseQueuePanel',
    phase: '3',
    purpose: 'Phase実行キューを保存',
    containsSensitiveData: false,
    notes: 'Phase IDの配列。',
  },
  // Preview URL
  {
    key: 'darake.previewUrl.v1',
    owner: 'PreviewUrlRecordPanel',
    phase: '8',
    purpose: 'プレビューURL記録を保存',
    containsSensitiveData: false,
    notes: 'URLのリスト。認証情報含まない。',
  },
  // Screenshot
  {
    key: 'darake.screenshotJobDraft.v1',
    owner: 'ScreenshotJobDraftPanel',
    phase: '9',
    purpose: 'スクショジョブ下書きを保存',
    containsSensitiveData: false,
    notes: 'ジョブ設定テキスト。',
  },
  {
    key: 'darake.screenshotWorkflowDispatch.v1',
    owner: 'ScreenshotWorkflowDispatchDraftPanel',
    phase: '10',
    purpose: 'Workflow dispatch下書きを保存',
    containsSensitiveData: false,
    notes: 'YAMLテキスト。tokenは含まない。',
  },
  {
    key: 'darake.screenshotWorkflowFileStatus.v1',
    owner: 'ScreenshotWorkflowFileStatusPanel',
    phase: '10',
    purpose: 'Workflowファイル状態を保存',
    containsSensitiveData: false,
    notes: 'ファイルパス/ステータスのみ。',
  },
  {
    key: 'darake.screenshotCaptureManifest.v1',
    owner: 'ScreenshotCaptureManifestRecordPanel',
    phase: '10.26',
    purpose: 'スクショキャプチャマニフェストを保存',
    containsSensitiveData: false,
    notes: 'マニフェスト情報。',
  },
  {
    key: 'darake.screenshotResultRecord.v1',
    owner: 'ScreenshotResultRecordPanel',
    phase: '10.27',
    purpose: 'スクショ結果記録を保存',
    containsSensitiveData: false,
    notes: '撮影結果の一覧。',
  },
  {
    key: 'darake.uiCheckResultRecord.v1',
    owner: 'UiCheckResultRecordPanel',
    phase: '10.30',
    purpose: 'UIチェック結果記録を保存',
    containsSensitiveData: false,
    notes: 'UIチェック結果の一覧。',
  },
  {
    key: 'darake.uiMachineCheckDraft.v1',
    owner: 'UiMachineCheckDraftPanel',
    phase: '10.29',
    purpose: 'UIマシンチェック下書きを保存',
    containsSensitiveData: false,
    notes: 'チェック設定テキスト。',
  },
  {
    key: 'darake.realCaptureWorkflowDraft.v1',
    owner: 'RealCaptureWorkflowDraftPanel',
    phase: '10',
    purpose: '実撮影workflow下書きを保存',
    containsSensitiveData: false,
    notes: 'YAMLテキスト。',
  },
  {
    key: 'darake.playwrightSetupDryRunDraft.v1',
    owner: 'PlaywrightSetupDryRunDraftPanel',
    phase: '10',
    purpose: 'Playwright dry run下書きを保存',
    containsSensitiveData: false,
    notes: '設定テキスト。',
  },
  {
    key: 'darake.playwrightSetupWorkflowFileStatus.v1',
    owner: 'PlaywrightSetupWorkflowFileStatusPanel',
    phase: '10',
    purpose: 'Playwright workflowファイル状態を保存',
    containsSensitiveData: false,
    notes: 'ファイルパス/ステータスのみ。',
  },
  {
    key: 'darake.playwrightSetupReportRecord.v1',
    owner: 'PlaywrightSetupReportRecordPanel',
    phase: '10',
    purpose: 'Playwright実行記録を保存',
    containsSensitiveData: false,
    notes: 'レポート記録。',
  },
  {
    key: 'darake.limitedScreenshotCaptureWorkflowDraft.v1',
    owner: 'LimitedScreenshotCaptureWorkflowDraftPanel',
    phase: '10',
    purpose: '限定スクショworkflow下書きを保存',
    containsSensitiveData: false,
    notes: 'YAMLテキスト。',
  },
  {
    key: 'darake.limitedScreenshotCaptureWorkflowFileStatus.v1',
    owner: 'LimitedScreenshotCaptureWorkflowFileStatusPanel',
    phase: '10',
    purpose: '限定スクショファイル状態を保存',
    containsSensitiveData: false,
    notes: 'ファイルパス/ステータスのみ。',
  },
  {
    key: 'darake.dryRunArtifactCheckRecord.v1',
    owner: 'DryRunArtifactCheckRecordPanel',
    phase: '10',
    purpose: 'Dry run成果物確認記録を保存',
    containsSensitiveData: false,
    notes: '確認記録。',
  },
  // Notification
  {
    key: 'darake.notificationDraft.v1',
    owner: 'NotificationDraftPanel',
    phase: '11',
    purpose: '通知下書きを保存',
    containsSensitiveData: false,
    notes: '通知テキスト。webhook URLは含まない。',
  },
  // App Store
  {
    key: 'darake.appStoreMetadata.v1',
    owner: 'AppStoreMetadataDraftPanel',
    phase: '12',
    purpose: 'App Storeメタデータ下書きを保存',
    containsSensitiveData: false,
    notes: 'テキスト情報のみ。API keyなし。',
  },
  {
    key: 'darake.privacyAgeRating.v1',
    owner: 'PrivacyAgeRatingDraftPanel',
    phase: '12',
    purpose: 'プライバシー・年齢制限設定を保存',
    containsSensitiveData: false,
    notes: '設定テキストのみ。',
  },
  // Submission
  {
    key: 'darake.submissionControlRoom.v1',
    owner: 'SubmissionControlRoomPanel',
    phase: '13',
    purpose: '提出管制室の状態を保存',
    containsSensitiveData: false,
    notes: 'チェック状態フラグ。',
  },
  {
    key: 'darake.appStoreConnectInputPack.v1',
    owner: 'AppStoreConnectInputPackPanel',
    phase: '13',
    purpose: 'App Store Connect入力パックを保存',
    containsSensitiveData: false,
    notes: 'アプリ情報テキスト。API keyなし。',
  },
  {
    key: 'darake.finalSubmissionGate.v1',
    owner: 'FinalSubmissionGatePanel',
    phase: '13',
    purpose: '最終提出ゲートの確認状態を保存',
    containsSensitiveData: false,
    notes: 'boolean フラグのみ。',
  },
  // Rejection
  {
    key: 'darake.appReviewRejection.v1',
    owner: 'AppReviewRejectionRecordPanel',
    phase: '14',
    purpose: 'リジェクト記録を保存',
    containsSensitiveData: false,
    notes: 'リジェクト内容テキスト。',
  },
  {
    key: 'darake.appReviewResponseDraft.v1',
    owner: 'AppReviewResponseDraftPanel',
    phase: '14',
    purpose: '審査回答下書きを保存',
    containsSensitiveData: false,
    notes: '回答テキスト。',
  },
  {
    key: 'darake.rejectionFixIssueDraft.v1',
    owner: 'RejectionFixIssueDraftPanel',
    phase: '14',
    purpose: 'リジェクト修正Issue下書きを保存',
    containsSensitiveData: false,
    notes: 'Issue下書きテキスト。',
  },
  // Post-Release / Portfolio
  {
    key: 'darake.releaseRecord.v1',
    owner: 'ReleaseRecordPanel / DarakeHomeSummaryPanel',
    phase: '15 / 16',
    purpose: 'リリース記録を保存',
    containsSensitiveData: false,
    notes: 'リリース情報の配列。',
  },
  {
    key: 'darake.postReleaseFeedback.v1',
    owner: 'PostReleaseFeedbackPanel',
    phase: '15',
    purpose: 'リリース後フィードバックを保存',
    containsSensitiveData: false,
    notes: 'フィードバックテキストの配列。',
  },
  {
    key: 'darake.nextUpdatePlan.v1',
    owner: 'NextUpdatePlanPanel',
    phase: '15',
    purpose: '次回更新計画を保存',
    containsSensitiveData: false,
    notes: '計画テキスト。',
  },
  {
    key: 'darake.appRegistry.v1',
    owner: 'AppRegistryPanel / DarakeHomeSummaryPanel',
    phase: '16',
    purpose: 'アプリ一覧を保存',
    containsSensitiveData: false,
    notes: 'アプリ情報の配列。',
  },
  // Templates
  {
    key: 'darake.savedBlueprints.v1',
    owner: 'SavedBlueprintsPanel',
    phase: '17',
    purpose: '保存済み設計書を保存',
    containsSensitiveData: false,
    notes: '設計書テキストの配列。',
  },
  // External Notification
  {
    key: 'darake.externalNotificationChannels.v1',
    owner: 'ExternalNotificationChannelPanel',
    phase: '19',
    purpose: '外部通知チャンネル設定を保存',
    containsSensitiveData: false,
    notes: 'チャンネル名のみ。URL/token含まない。',
  },
  {
    key: 'darake.webhookPayloadDraft.v1',
    owner: 'WebhookPayloadDraftPanel',
    phase: '19',
    purpose: 'Webhook payload下書きを保存',
    containsSensitiveData: false,
    notes: 'JSONテキスト。webhook URLは含まない。',
  },
  // GitHub Semi-Automation
  {
    key: 'darake.githubOperationCandidate.v1',
    owner: 'GitHubOperationCandidatePanel',
    phase: '20',
    purpose: 'GitHub操作候補設定を保存',
    containsSensitiveData: false,
    notes: 'GitHub tokenは含まない。',
  },
  {
    key: 'darake.workflowDispatchCandidate.v1',
    owner: 'WorkflowDispatchCandidateDraftPanel',
    phase: '20',
    purpose: 'workflow dispatch候補下書きを保存',
    containsSensitiveData: false,
    notes: 'YAMLテキスト。tokenは含まない。',
  },
  // AI Review
  {
    key: 'darake.aiReviewInputPack.v1',
    owner: 'AiReviewInputPackPanel',
    phase: '21',
    purpose: 'AIレビュー入力パックを保存',
    containsSensitiveData: false,
    notes: 'レビュー対象テキスト。AI API keyなし。',
  },
  {
    key: 'darake.aiReviewResultRecord.v1',
    owner: 'AiReviewResultRecordPanel',
    phase: '21',
    purpose: 'AIレビュー結果記録を保存',
    containsSensitiveData: false,
    notes: 'レビュー結果テキスト。',
  },
  {
    key: 'darake.aiReviewFixIssueDraft.v1',
    owner: 'AiReviewFixIssueDraftPanel',
    phase: '21',
    purpose: 'AIレビュー修正Issue下書きを保存',
    containsSensitiveData: false,
    notes: 'Issue下書きテキスト。',
  },
  // Revenue / Operations
  {
    key: 'darake.monetizationPlan.v1',
    owner: 'MonetizationPlanPanel',
    phase: '22',
    purpose: '収益化計画メモを保存',
    containsSensitiveData: false,
    notes: '計画テキスト。',
  },
  {
    key: 'darake.launchPromotionMemo.v1',
    owner: 'LaunchPromotionMemoPanel',
    phase: '22',
    purpose: 'ローンチプロモーションメモを保存',
    containsSensitiveData: false,
    notes: 'メモテキスト。',
  },
  // App Studio Factory
  {
    key: 'darake.appIdeaBatch.v1',
    owner: 'AppIdeaBatchPanel',
    phase: '23',
    purpose: 'アプリアイデア一覧を保存',
    containsSensitiveData: false,
    notes: 'アイデアテキストの配列。',
  },
  {
    key: 'darake.appFactoryRoadmap.v1',
    owner: 'AppFactoryRoadmapPanel',
    phase: '23',
    purpose: 'アプリファクトリーロードマップを保存',
    containsSensitiveData: false,
    notes: 'ロードマップテキスト。',
  },
  // Phase 92 / 97-99 新規キー
  {
    key: 'darake.previewDeployStatus.v1',
    owner: 'PreviewDeployStatusPanel',
    phase: '97',
    purpose: 'Preview URL とデプロイ状態を保存',
    containsSensitiveData: false,
    notes: 'フェーズ名・URL・デプロイ状態のみ。tokenなし。',
  },
  {
    key: 'darake.appStorePrepMode.v1',
    owner: 'AppStorePrepModePanel',
    phase: '99',
    purpose: 'App Store提出準備チェックリストの状態を保存',
    containsSensitiveData: false,
    notes: 'チェック済みID一覧とアプリ名のみ。',
  },
  {
    key: 'darake.appCreationFlow.v1',
    owner: 'AppCreationFlowPanel',
    phase: '98',
    purpose: '9ステップ制作フローの進行状態を保存',
    containsSensitiveData: false,
    notes: 'アプリ名・アイデア・現在ステップのみ。',
  },
  {
    key: 'darake.setupHubV2.doneSteps.v1',
    owner: 'SetupHubV2Panel',
    phase: '92',
    purpose: 'Setup Hubの完了済みステップを保存',
    containsSensitiveData: false,
    notes: '完了済みStep IDのみ。',
  },
  {
    key: 'darake.prCiHuman.lastQuery.v1',
    owner: 'PrCiHumanSummaryPanel',
    phase: '103',
    purpose: 'PR/CI実データ確認の最後のrepoUrl・PR番号を保存',
    containsSensitiveData: false,
    notes: 'repoUrl文字列とprNumber文字列のみ。tokenなし。',
  },
  {
    key: 'darake.prCiHuman.lastStatus.v1',
    owner: 'PrCiHumanSummaryPanel',
    phase: '105',
    purpose: '最後に取得したPR/CI状態をDeep Build連携用に保存',
    containsSensitiveData: false,
    notes: 'PR URL・番号・CI/レビュー状態のみ。tokenなし。',
  },
  {
    key: 'darake.workSession.current.v1',
    owner: 'DarakeCurrentWorkPanel',
    phase: '105',
    purpose: '進行中のWorkSession本体を保存',
    containsSensitiveData: false,
    notes: 'アプリ名・Issue/PR/Preview URL・次アクションのみ。tokenなし。',
  },
  {
    key: 'darake.workSession.history.v1',
    owner: 'DarakeCurrentWorkPanel',
    phase: '105',
    purpose: '直近のWorkSession履歴を保存',
    containsSensitiveData: false,
    notes: '履歴20件まで。secret/tokenは保存しない。',
  },
];

export function formatLocalStorageKeyRegistryMarkdown(
  items: LocalStorageKeyRegistryItem[],
): string {
  const lines: string[] = [
    '# LocalStorage Key Registry',
    `Total: ${items.length}件`,
    '',
    '## キー一覧',
    '| key | owner | phase | sensitive |',
    '|-----|-------|-------|-----------|',
    ...items.map(
      (i) =>
        `| \`${i.key}\` | ${i.owner} | ${i.phase} | ${i.containsSensitiveData ? '⚠️ YES' : 'no'} |`,
    ),
    '',
    '## 安全方針',
    '- secret / token / API key / webhook URL はlocalStorageに保存しない',
    '- 全キーのcontainsSensitiveDataはfalse',
    '- 新しいキーを追加する際はこのRegistryに登録する',
  ];
  return lines.join('\n');
}
