// Wake Action Token: short-lived tokens that encode a single required user action.
// Generated by Worker when a wake notification is sent.
// Stored in RUN_REGISTRY_KV with a 24-hour TTL.

const TOKEN_PREFIX = 'wake-token:';
const TOKEN_TTL_SECONDS = 24 * 60 * 60; // 24 hours

export type WakeActionKind =
  | 'open-pr'
  | 'send-fix-request'
  | 'copy-fallback-instruction'
  | 'open-issue'
  | 'show-setup'
  | 'show-details';

export type WakeActionTokenRecord = {
  tokenId: string;
  runId: string;
  reason: string;
  actionKind: WakeActionKind;
  actionUrl?: string;
  prUrl?: string;
  prNumber?: number;
  issueUrl?: string;
  issueNumber?: number;
  // stored for send-fix-request execution
  repoUrl?: string;
  fixRequestBody?: string;
  message: string;
  nextActionLabel: string;
  expiresAt: string;
  usedAt?: string;
  createdAt: string;
};

export function createTokenId(): string {
  return `wat-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

export function buildWakeActionToken(
  params: Omit<WakeActionTokenRecord, 'tokenId' | 'createdAt' | 'expiresAt'>,
): WakeActionTokenRecord {
  const now = new Date();
  const expiresAt = new Date(now.getTime() + TOKEN_TTL_SECONDS * 1000).toISOString();
  return {
    ...params,
    tokenId: createTokenId(),
    createdAt: now.toISOString(),
    expiresAt,
  };
}

export async function saveWakeActionToken(
  kv: KVNamespace,
  token: WakeActionTokenRecord,
): Promise<void> {
  const ttl = Math.max(1, Math.floor((new Date(token.expiresAt).getTime() - Date.now()) / 1000));
  await kv.put(`${TOKEN_PREFIX}${token.tokenId}`, JSON.stringify(token), {
    expirationTtl: ttl,
  });
}

export async function getWakeActionToken(
  kv: KVNamespace,
  tokenId: string,
): Promise<WakeActionTokenRecord | null> {
  const raw = await kv.get(`${TOKEN_PREFIX}${tokenId}`);
  if (!raw) return null;
  try {
    return JSON.parse(raw) as WakeActionTokenRecord;
  } catch {
    return null;
  }
}

export async function markTokenUsed(
  kv: KVNamespace,
  token: WakeActionTokenRecord,
): Promise<void> {
  const updated: WakeActionTokenRecord = {
    ...token,
    usedAt: new Date().toISOString(),
  };
  const remainingTtl = Math.max(
    1,
    Math.floor((new Date(token.expiresAt).getTime() - Date.now()) / 1000),
  );
  await kv.put(`${TOKEN_PREFIX}${token.tokenId}`, JSON.stringify(updated), {
    expirationTtl: remainingTtl,
  });
}
